# jokes.py
# This program tells jokes
# Clinton Peterson
# 04 Apr 2017

# Here come the jokes
print("I'm jokebot, please type your name and press enter.")
name = input() 
print("Cool, don't care "+name+". Ready for some jokes? (press enter to continue)")
input() 
print("Did you say yes or no? Say it out loud please. (press enter to continue)")
input() 
print("Well too bad, you are getting jokes regardless. (press enter to continue)")
input() 
print("I'm sick of telling you how to continue, so from here on out just press enter.")
input() 
print("Joke 1")
input()
print("What time did the man go to the dentist?")
input() 
print("Tooth hurt-y!")
input()
print("Joke 2")
input()
print("Did you hear about the guy who invented Lifesavers?") 
input()
print("They say he made a mint!")
input()
print("Joke 3")
input()
print("Why do chicken coops only have two doors?") 
input()
print("Because if they had four, they would be chicken sedans!")
input()
print("Joke 4")
input()
print("Why did the Clydesdale give the pony a glass of water?")
input()
print("Because he was a little horse!")
input()
print("Joke 5")
input()
print("How do you make a Kleenex dance?") 
input()
print("Put a little boogie in it!")
input()
print("Ok, no more jokes...bye")
input()
